### ISSUE TITLE
difference in data between old/new pipeline

### ISSUE THREAD

**Issue by romanchyla** [adsabs/AdsDataSqlSync#60]
for 'data' field, old solr index has 'CDS', the new has 'SIMBAD'

this is what i see in the nonbib table; @golnazads or @aaccomazzi can you tell if it is ok, or we might be missing something?

```
data_pipeline=> select * from nonbib.datalinks where bibcode = '2015ApJ...815L...1T';
       bibcode       | link_type | link_sub_type |                          url                           |         title          | item_count 
---------------------+-----------+---------------+--------------------------------------------------------+------------------------+------------
 2015ApJ...815L...1T | ARTICLE   | EPRINT_HTML   | {http://arxiv.org/abs/1511.04460}                      | {}                     |          0
 2015ApJ...815L...1T | ARTICLE   | EPRINT_PDF    | {http://arxiv.org/pdf/1511.04460}                      | {}                     |          0
 2015ApJ...815L...1T | ARTICLE   | PUB_HTML      | {http://dx.doi.org/10.1088%2F2041-8205%2F815%2F1%2FL1} | {}                     |          0
 2015ApJ...815L...1T | ARTICLE   | PUB_PDF       | {http://stacks.iop.org/2041-8205/815/L1/pdf}           | {}                     |          0
 2015ApJ...815L...1T | DATA      | SIMBAD        | {http://$SIMBAD$/simbo.pl?bibcode=2015ApJ...815L...1T} | {"SIMBAD Objects (1)"} |          1
(5 rows)
```

**Comment by golnazads** [comment]
The new data also has CDS, here is the list of all data sub types

# data sub types
data =  [
   'ARI', 'SIMBAD', 'NED', 'CDS', 'Vizier', 'GCPD', 'Author', 'PDG',
'MAST', 'HEASARC', 'INES', 'IBVS', 'Astroverse',
   'ESA', 'NExScI', 'PDS', 'AcA', 'ISO', 'ESO', 'CXO', 'NOAO', 'XMM',
'Spitzer', 'PASA', 'ATNF', 'KOA', 'Herschel',
   'GTC', 'BICEP2', 'ALMA', 'CADC', 'Zenodo', 'TNS', ''
]

golnaz

**Comment by romanchyla** [comment]
i'm not sure where that data comes from @golnazads - Steve ran nonbib pipeline yesterday and there were no changes in the code in the meantime; so the record in question - should it have SIMBAD?

**Comment by golnazads** [comment]
Yes, it think so. that is what I also get in my local db that I created
while back. I think it should be SIMBAD.

data_pipeline=# select * from nonbib.datalinks where
bibcode='2015ApJ...815L...1T';

       bibcode       | link_type | link_sub_type |
url                           |         title          | item_count

---------------------+-----------+---------------+--------------------------------------------------------+------------------------+------------

 2015ApJ...815L...1T | ARTICLE   | EPRINT_HTML   | {
http://arxiv.org/abs/1511.04460}                      | {}
    |          0

 2015ApJ...815L...1T | ARTICLE   | EPRINT_PDF    | {
http://arxiv.org/pdf/1511.04460}                      | {}
    |          0

 2015ApJ...815L...1T | ARTICLE   | PUB_HTML      | {
http://dx.doi.org/10.1088%2F2041-8205%2F815%2F1%2FL1} | {}
    |          0

 2015ApJ...815L...1T | ARTICLE   | PUB_PDF       | {
http://stacks.iop.org/2041-8205/815/L1/pdf}           | {}
    |          0

 2015ApJ...815L...1T | DATA      | SIMBAD        | {http://$SIMBAD$/
simbo.pl?bibcode=2015ApJ...815L...1T} | {"SIMBAD Objects (1)"} |          1

(5 rows)

you think the last record used to be CDS in nonbib?

just checked solr for links_data and here is what is there

"links_data":["{\"title\":\"\", \"type\":\"simbad\", \"instances\":\"1\",
\"access\":\"\"}", "{\"title\":\"\", \"type\":\"pdf\", \"instances\":\"\",
\"access\":\"open\"}", "{\"title\":\"\", \"type\":\"preprint\",
\"instances\":\"\", \"access\":\"open\"}", "{\"title\":\"\",
\"type\":\"electr\", \"instances\":\"\", \"access\":\"open\"}"],

**Comment by aaccomazzi** [comment]
I checked the source file, SIMBAD is correct.  We made changes in the way we structure links over the past month so now we consistently create the same labels for the "data" solr field and the datalinks table.  So some changes in "data" are to be expected.
