### ISSUE TITLE
Compute complete properties field

### ISSUE THREAD

**Issue by spacemansteve** [adsabs/AdsDataSqlSync#70]
Historically, the Solr properties field was computed by the bib ingest code.  With datalinks, we are computing new attributes for Solr property field.  Rather than requiring the master pipeline to merge the property field from two pipelines, the nonbib pipeline should generate a complete property field.

The nonbib code will have to compute some new values (OPENACCESS) based on values currently read in (html pub, epub, etc.).  nonbib may need to process additional ingest files to compute a complete properties field.

**Comment by aaccomazzi** [comment]
This is how the elements of the property fields were computed in the bib pipeline: https://github.com/adsabs/ADSimportpipeline/blob/master/aip/libs/solr_adapter.py#L437

Happy to walk through them with you to see if everything needed is already in nonbib, else suggest.

**Comment by spacemansteve** [comment]
Is this a complete list of fields that need to be set in property: https://github.com/adsabs/adspy/blob/master/ADSCachedExports.py#L1190
